version: '3'

services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - mr-data-test-workspace:/tmp/spark_output
    networks:
      - mr-data-test-network
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - '8081:8081'
    volumes:
      - mr-data-test-workspace:/tmp/spark_output
    networks:
      - mr-data-test-network
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'

  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - '8082:8081'
    volumes:
      - mr-data-test-workspace:/tmp/spark_output
    networks:
      - mr-data-test-network
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'

networks:
  mr-data-test-network:
    name: 'mr-data-test-network'
    driver: bridge

volumes:
  mr-data-test-workspace:
    name: 'mr-data-test-workspace'
    driver: local
